# .goreleaser.yaml
---
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: wc-cli
    main: ./cmd/cli-wc/
    binary: cli-wc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goamd64:
      - v1
      - v2
      - v3
      - v4
    ldflags:
      - -s -w
    ignore:
      - goos: windows
        goarch: arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: '.checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
