#!/bin/bash

echo go generate ./...
time go generate ./...
printf "\n"

echo go "$@"
time go "$@"
printf "\n"

echo git restore ./cmd/*/.version.txt
time git restore ./cmd/*/.version.txt
printf "\n"

echo git restore ./cmd/*/.app_info.txt
time git restore ./cmd/*/.app_info.txt
printf "\n"
