#
# .github/workflows/codacy-go.yml
#

# https://github.com/codacy/codacy-coverage-reporter-action
# https://docs.codacy.com/coverage-reporter/alternative-ways-of-running-coverage-reporter/
# https://docs.codacy.com/v6.0/coverage-reporter/#submitting-coverage-for-golang
---

name: codacy-coverage-reporter

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter

    steps:
      - uses: actions/checkout@v2

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}

          language: go
          coverage-reports: cobertura.xml
