---
#
# .github/workflows/dagger-go.yml
#
# https://docs.dagger.io/cookbook/#github-actions
name: 'Dagger CI - Go'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: Install Dagger CLI
        run: ./scripts/dagger-install-cli
      - name: Lint with Dagger
        run: ./scripts/dagger-run-lint
      - name: Test with Dagger
        run: ./scripts/dagger-run-test
      - name: Build with Dagger
        run: |-
          ./scripts/dagger-run-build
          sudo apt install -y tree
          {
            printf "\`\`\`text\n"
            tree ./build
            printf "\`\`\`\n"
          } | tee -a "${GITHUB_STEP_SUMMARY}"
      - name: Create Release Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |-
          sudo apt install -y zip
          ./scripts/create-release-files
      - name: Publish Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "release/releases.tar.gz,release/releases.zip"
          bodyFile: release/release_body.md
