---
#
# .github/workflows/dagger-go.yml
#
# https://docs.dagger.io/cookbook/#github-actions
name: 'Dagger CI - Go'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: Install Dagger CLI
        run: ./scripts/dagger-install-cli
      - name: Lint with Dagger
        run: ./scripts/dagger-run-lint
      - name: Test with Dagger
        run: ./scripts/dagger-run-test
      - name: Build with Dagger
        run: |-
          ./scripts/dagger-run-build
          sudo apt install -y tree
          {
            printf "\`\`\`text\n"
            tree ./build
            printf "\`\`\`\n"
          } | tee -a "${GITHUB_STEP_SUMMARY}"
      - name: Create Release Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |-
          sudo apt install -y zip
          {
            printf "\`\`\`text\n"
            echo Running: tar cvzf releases.tar.gz build/*/*
            time tar cvzf releases.tar.gz build/*/*
            printf "\`\`\`\n"
            printf "\n"
            printf "\`\`\`text\n"
            echo Running: zip -r releases.zip build/*/*
            time zip -r releases.zip build/*/*
            printf "\`\`\`\n"
            printf "\n"
            printf "\`\`\`text\n"
            echo Running: ./scripts/git-release-notes release-short "${GITHUB_REF_NAME}" '2>/dev/null' \| tee release_body.md
            ./scripts/git-release-notes release-short "${GITHUB_REF_NAME}" 2>/dev/null | tee release_body.md
            printf "\`\`\`\n"
          } | tee -a "${GITHUB_STEP_SUMMARY}"
      - name: Publish Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "releases.tar.gz,releases.zip"
          bodyFile: release_body.md
