---
#
#  .github/workflows/github-pages-hugo.yml
#
name: Deploy Hugo site to GitHub Pages
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'pages-pr'
  pull_request:
    branches:
      - 'pages-pr'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # Build job
  stage2-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Hugo
        id: setup-hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Setup Pages
        id: setup_pages
        uses: actions/configure-pages@v2
      - name: Setup NodeJS
        id: setup-nodejs
        uses: actions/setup-node@v4
        with:
          # https://nodejs.org/en/about/releases/
          node-version: lts/*
      - run: |
          node -v
          npm install --save-dev autoprefixer
          npm install --save-dev postcss-cli
          npm install -D postcss
          (cd pages-gh/themes/docsy && npm install)
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          cd pages-gh/
          hugo \
            --minify \
            --baseURL "${{ steps.setup_pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages-gh/public

  # Deployment job
  stage3-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: stage2-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
