#
# .github/workflows/links.yml
#

# https://github.com/lycheeverse/lychee-action
---

name: Link Check Workflow

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop

  pull_request:

defaults:
  run:
    shell: bash

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
