#
# .github/workflows/misspell.yml
#

# https://github.com/reviewdog/action-misspell
---

name: Spelling Workflow

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop

  pull_request:

env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  spelling:
    name: Spelling Check
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run misspell
        uses: reviewdog/action-misspell@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
          level: error
          locale: "US"
          reporter: github-check
